apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: developerapps.apigee.google.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: apigee.google.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Age
        jsonPath: .metadata.creationTimestamp
        type: date
      - name: ConsumerKey
        jsonPath: .status.consumerKey
        description: Consumer Key
        type: string
      schema:
        openAPIV3Schema:
          description: DeveloperApp is the Schema for the developerapps API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: DeveloperAppSpec defines the desired state of DeveloperApp
              properties:
                org:
                  type: string
                developer_email:
                  type: string
                apiProducts:
                  items:
                    type: string
                  type: array
                attributes:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                callbackUrl:
                  type: string
                credentials:
                  items:
                    properties:
                      apiProducts:
                        items:
                          properties:
                            apiproduct:
                              type: string
                            status:
                              type: string
                          type: object
                        type: array
                      attributes:
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      consumerKey:
                        type: string
                      consumerSecret:
                        type: string
                      expiresAt:
                        type: integer
                      scopes:
                        items:
                          type: string
                        type: array
                      status:
                        type: string
                    required:
                    - attributes
                    type: object
                  type: array
                name:
                  description: Foo is an example field of DeveloperApp. Edit DeveloperApp_types.go
                    to remove/update
                  type: string
                scopes:
                  items:
                    type: string
                  type: array
                conusmerKey:
                  type: string
              type: object
            status:
              description: DeveloperAppStatus defines the observed state of DeveloperApp
              properties:
                consumerKey:
                  description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                    of cluster Important: Run "make" to regenerate code after modifying
                    this file'
                  type: string
                consumerSecret:
                  type: string
              type: object
          type: object
# either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: developerapps
    # singular name to be used as an alias on the CLI and for display
    singular: developerapp
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DeveloperApp
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - devapps 
