apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: developerappcredentials.apigee.google.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: apigee.google.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: AppName
        jsonPath: .spec.name
        description: App Name
        type: string
      - name: ConsumerKey
        jsonPath: .consumerKey
        description: Consumer Key
        type: string
      - name: Developer
        jsonPath: .developer_email
        type: date
      schema:
        openAPIV3Schema:
          description: DeveloperApp Credentials is the Schema for the developerapps credentials. Populated on
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: DeveloperAppSpec defines the desired state of DeveloperApp
              properties:
                developer_email:
                  type: string
                name:
                  description: Foo is an example field of DeveloperApp. Edit DeveloperApp_types.go
                    to remove/update
                  type: string
                conusmerKey:
                  type: string
              type: object
          type: object
# either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: developerappcredentials
    # singular name to be used as an alias on the CLI and for display
    singular: developerappcredential
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DeveloperAppCredential
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - appcr
    - appcreds
