apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigee-controller
  namespace: apigee-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigee-controller
  template:
    metadata:
      labels:
        app: apigee-controller
    spec:
      containers:
      - name: controller
        image: gcr.io/%%PRODUCT_ID%%/apigee-controller:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: sa
          mountPath: /sa
          readOnly: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - name: sa
        secret:
          secretName: serviceaccount
          defaultMode: 0444
---
apiVersion: v1
kind: Service
metadata:
  name: apigee-controller
  namespace: apigee-config
spec:
  selector:
    app: apigee-controller
  ports:
  - port: 80
    targetPort: 8080
