apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: apiproducts.apigee.google.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: apigee.google.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: apiproduct is the Schema for the apiproducts API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: ApiProductSpec defines the desired state of ApiProduct
              properties:
                org:
                  type: string
                apiResources:
                  items:
                    type: string
                  type: array
                approvalType:
                  type: string
                attributes:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                description:
                  type: string
                displayName:
                  type: string
                environments:
                  items:
                    type: string
                  type: array
                operationGroup:
                  properties:
                    operationConfigs:
                      items:
                        properties:
                          apiSource: 
                            type: string
                          operations:
                            items:
                              properties:
                                resource: 
                                  type: string
                                methods:
                                  items:
                                    type: string
                                  type: array
                              type: object
                            type: array
                          quota:
                            properties:
                              limit:
                                type: string
                              interval:
                                type: string
                              timeUnit: 
                                type: string
                            type: object
                        type: object
                      type: array
                    operationConfigType:
                      type: string
                  type: object
                name:
                  type: string
                proxies:
                  items:
                    type: string
                  type: array
                quota:
                  type: string
                quotaInterval:
                  type: string
                quotaTimeUnit:
                  type: string
                scopes:
                  items:
                    type: string
                  type: array
              required:
              - attributes
              type: object
            status:
              description: ApiProductStatus defines the observed state of ApiProduct
              type: object
          type: object
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: apiproducts
    # singular name to be used as an alias on the CLI and for display
    singular: apiproduct
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: APIProduct
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - apipr
