apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: apigee-apiproduct-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: apigee.google.com/v1
    resource: apiproducts
  childResources:
  - apiVersion: apigee.google.com/v1
    resource: restfuloperations
  - apiVersion: apigee.google.com/v1
    resource: apiprodudcts
  hooks:
    sync:
      webhook:
        url: http://apigee-controller.apigee-config/apiproduct/sync
    finalize:
      webhook:
        url: http://apigee-controller.apigee-config/apiproduct/finalize

