apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: apigee-app-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: apigee.google.com/v1
    resource: developerapps
  childResources:
  - apiVersion: apigee.google.com/v1
    resource: developerappcredentials
  hooks:
    sync:
      webhook:
        url: http://apigee-controller.apigee-config/developerapp/sync
    finalize:
      webhook:
        url: http://apigee-controller.apigee-config/developerapp/finalize

